# Generated by Django 3.2.7 on 2021-09-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.TextField(default='2021-09-25 21:50:09')),
                ('user', models.CharField(default='No User', max_length=150)),
                ('product_item', models.TextField(default='No item')),
                ('qty', models.BigIntegerField(default=0)),
                ('price', models.BigIntegerField(default=0)),
                ('paid', models.BooleanField(default=False)),
                ('checkout_time', models.TextField(default='2021-09-25 21:50:09')),
            ],
        ),
    ]
