# Generated by Django 3.2.7 on 2021-09-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='No User', max_length=150)),
                ('checkout_time', models.TextField(default='2021-09-25 23:33:57')),
            ],
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='checkout_time',
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='order_time',
            field=models.TextField(default='2021-09-25 23:33:57'),
        ),
    ]
