# Generated by Django 3.2.7 on 2021-09-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210925_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='order_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='checkout_time',
            field=models.TextField(default='2021-09-25 23:36:36'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='order_time',
            field=models.TextField(default='2021-09-25 23:36:36'),
        ),
    ]
