# Generated by Django 3.2.7 on 2021-09-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210925_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='checkout_time',
            field=models.TextField(default='2021-09-26 10:46:49'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='order_time',
            field=models.TextField(default='2021-09-26 10:46:49'),
        ),
    ]
